version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: Proj_db #เปลี่ยน
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8811:3306" #เปลี่ยน
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - weblab820
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: Project_db #เปลี่ยน
    environment:
      PMA_HOST: Proj_db #เปลี่ยน
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8812:80" #เปลี่ยน
    depends_on:
      - db
    networks:
      - weblab820
    restart: always

networks:
  weblab820:
    driver: bridge

volumes:
  mysql_data:
    driver: local